development:
  adapter: postgresql
  encoding: unicode
  database: employeeengagement_development
  pool: 2
  min_messages: warning

test: &test
  adapter: postgresql
  encoding: unicode
  database: employeeengagement_test
  pool: 2
  min_messages: error