# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 956171a44172d2f88f44acd5f076f37f9d8989dd3b2e2b8279f84331de919605c1a160da02c8dd0e5e4b230a28001a3deb6852221ba609d330b1dc4ea79f5b42

test:
  secret_key_base: 5bc71fde24d0efe50f585fc00c36cb3bddb57fc09b4be07cc9d5a861b33dfa9a4b9806e47bea2ada8dbc942d5201d7a221febaa27a2b211490a787d30dda39dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
